#!/bin/sh
dir=`dirname $0`
(echo "//! Minidump structure definitions (autogenerated from C headers).
//!
//! This file is automatically generated from Breakpad's [minidump_format.h][1]
//! using [rust-bindgen][2].
//! [1]: https://chromium.googlesource.com/breakpad/breakpad/+/master/src/google_breakpad/common/minidump_format.h
//! [2]: https://github.com/crabtw/rust-bindgen
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
"; $dir/../rust-bindgen/target/debug/bindgen -I $dir/../breakpad/src/src/ $dir/../breakpad/src/src/google_breakpad/common/minidump_format.h) | sed 's/#\[repr(C)\]/#\[repr(C, packed)\]/' > src/minidump_format.rs
